name: Deploy API

on:
  push:
    branches: [main]

jobs:
  docker-build-push:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: docker setup
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f #v3.12.0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef #v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 #v6.18.0
        with:
          push: true
          tags: |
            ghcr.io/ayushshende25/pizza-box-api:latest
            ghcr.io/ayushshende25/pizza-box-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-24.04
    needs: docker-build-push

    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@823bd89e131d8d508129f9443cad5855e9ba96f0 #v1.2.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /opt/pizza-box

            echo "IMAGE_TAG=${{ github.sha }}" > .env.deploy 

            docker stack deploy \
              --env-file .env.deploy \
              -c docker-stack.yaml \
              pizza-box
